export const CREATE_INVENTORY_ITEM = "CREATE_INVENTORY_ITEM";
export const CREATE_INVENTORY_ITEM_SUCCESS = "CREATE_INVENTORY_ITEM_SUCCESS";
export const CREATE_INVENTORY_ITEM_FAILED = "CREATE_INVENTORY_ITEM_FAILED";

export const GET_INVENTORY_ITEM = "GET_INVENTORY_ITEM";
export const GET_INVENTORY_ITEM_SUCCESS = "GET_INVENTORY_ITEM_SUCCESS";
export const GET_INVENTORY_ITEM__FAILED = "GET_INVENTORY_ITEM__FAILED";

export const UPDATE_INVENTORY_ITEM = "UPDATE_INVENTORY_ITEM";
export const UPDATE_INVENTORY_ITEM_SUCCESS = "UPDATE_INVENTORY_ITEM_SUCCESS";
export const UPDATE_INVENTORY_ITEM_FAILED = "UPDATE_INVENTORY_ITEM_FAILED";

export const DELETE_INVENTORY_ITEM = "DELETE_INVENTORY_ITEM";
export const DELETE_INVENTORY_ITEM_SUCCESS = "DELETE_INVENTORY_ITEM_SUCCESS";
export const DELETE_INVENTORY_ITEM_FAILED = "DELETE_INVENTORY_ITEM_FAILED";

export const GET_INVENTORY_ITEMS = "GET_INVENTORY_ITEMS";
export const GET_INVENTORY_ITEMS_SUCCESS = "GET_INVENTORY_ITEMS_SUCCESS";
export const GET_INVENTORY_ITEMS__FAILED = "GET_INVENTORY_ITEMS__FAILED";

export const CREATE_INDEXED_DB_INVENTORY_ITEM =
  "CREATE_INDEXED_DB_INVENTORY_ITEM";
export const CREATE_INDEXED_DB_INVENTORY_ITEM_SUCCESS =
  "CREATE_INDEXED_DB_INVENTORY_ITEM_SUCCESS";
export const CREATE_INDEXED_DB_INVENTORY_ITEM_FAILED =
  "CREATE_INDEXED_DB_INVENTORY_ITEM_FAILED";

export const GET_INDEXED_DB_INVENTORY_ITEM = "GET_INDEXED_DB_INVENTORY_ITEM";
export const GET_INDEXED_DB_INVENTORY_ITEM_SUCCESS =
  "GET_INDEXED_DB_INVENTORY_ITEM_SUCCESS";
export const GET_INDEXED_DB_INVENTORY_ITEM__FAILED =
  "GET_INDEXED_DB_INVENTORY_ITEM__FAILED";

export const GET_INDEXED_DB_BY_INDEX_INVENTORY_ITEM =
  "GET_INDEXED_DB_BY_INDEX_INVENTORY_ITEM";
export const GET_INDEXED_DB_BY_INDEX_INVENTORY_ITEM_SUCCESS =
  "GET_INDEXED_DB_BY_INDEX_INVENTORY_ITEM_SUCCESS";
export const GET_INDEXED_DB_BY_INDEX_INVENTORY_ITEM__FAILED =
  "GET_INDEXED_DB_BY_INDEX_INVENTORY_ITEM__FAILED";

export const UPDATE_INDEXED_DB_INVENTORY_ITEM =
  "UPDATE_INDEXED_DB_INVENTORY_ITEM";
export const UPDATE_INDEXED_DB_INVENTORY_ITEM_SUCCESS =
  "UPDATE_INDEXED_DB_INVENTORY_ITEM_SUCCESS";
export const UPDATE_INDEXED_DB_INVENTORY_ITEM_FAILED =
  "UPDATE_INDEXED_DB_INVENTORY_ITEM_FAILED";

export const DELETE_INDEXED_DB_INVENTORY_ITEM =
  "DELETE_INDEXED_DB_INVENTORY_ITEM";
export const DELETE_INDEXED_DB_INVENTORY_ITEM_SUCCESS =
  "DELETE_INDEXED_DB_INVENTORY_ITEM_SUCCESS";
export const DELETE_INDEXED_DB_INVENTORY_ITEM_FAILED =
  "DELETE_INDEXED_DB_INVENTORY_ITEM_FAILED";

export const GET_INDEXED_DB_INVENTORY_ITEMS = "GET_INDEXED_DB_INVENTORY_ITEMS";
export const GET_INDEXED_DB_INVENTORY_ITEMS_SUCCESS =
  "GET_INDEXED_DB_INVENTORY_ITEMS_SUCCESS";
export const GET_INDEXED_DB_INVENTORY_ITEMS__FAILED =
  "GET_INDEXED_DB_INVENTORY_ITEMS__FAILED";

export const CLEAR_INDEXED_DB_INVENTORY_ITEMS =
  "CLEAR_INDEXED_DB_INVENTORY_ITEMS";
export const CLEAR_INDEXED_DB_INVENTORY_ITEMS_SUCCESS =
  "CLEAR_INDEXED_DB_INVENTORY_ITEMS_SUCCESS";
export const CLEAR_INDEXED_DB_INVENTORY_ITEMS__FAILED =
  "CLEAR_INDEXED_DB_INVENTORY_ITEMS__FAILED";
